# Generated by Django 3.1.3 on 2020-11-17 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1500)),
                ('title', models.TextField(max_length=1500)),
                ('pub_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date Published')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=1)),
                ('category', models.TextField(choices=[('POLITICS', 'Politics'), ('SPORTS', 'Sports'), ('BEAUTY', 'Beauty'), ('NATURE', 'Nature')], max_length=100, null=True)),
                ('ident', models.CharField(blank=True, default=uuid.uuid4, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fave_categories', models.TextField(blank=True, max_length=150, null=True)),
                ('DOB', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.websiteuser')),
            ],
        ),
    ]
