# Generated by Django 3.1.3 on 2020-11-17 21:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201117_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ident',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
