# Generated by Django 3.1.3 on 2020-11-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20201123_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='in_reply_to',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
