# Generated by Django 3.1.3 on 2020-11-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_dislike_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
    ]
