# Generated by Django 3.1.3 on 2020-11-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20201129_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='in_reply_to',
        ),
    ]
