# Generated by Django 3.1.3 on 2020-11-30 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_comment_in_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='in_reply_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.comment'),
        ),
    ]
